import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { ReduxProvider } from "@/app/providers/ReduxProvider"
import { Header } from "@/widgets/header/header"
import { Alert } from "@/features/alert/alert"
import { GoogleOAuthProvider } from "@react-oauth/google"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const googleClientId = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || ""

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <GoogleOAuthProvider clientId={googleClientId}>
          <ReduxProvider>
            <Header />
            {children}
            {/* Alert для вывода ошибок */}
            <Alert />
          </ReduxProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  )
}
